spring:
  datasource:
    url: jdbc:mysql://localhost:3306/petshop?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  mybatis:
    mapper-locations: classpath:com.msyq.psetshop.mapper/*.xml
    type-aliases-package: com.msyq.psetshop.entity
    configuration:
      map-underscore-to-camel-case: true
  #模板引擎
  freemarker:
    #关闭缓存
    cache: false
    request-context-attribute: request
    #模板加载的位置
    template-loader-path: classpath:/templates
    #前缀
    suffix: .html
    #后缀
    prefix: /html/
server:
  port: 8383
#logging:
#  level:
#     com.cuzj.backstage.demo.mapper: debug
